### ISSUE TITLE
Fails to install on OSX 

### ISSUE THREAD

**Issue by fluffy** [ietf-tools/RfcEditor#105]
pip install svgcheck

Collecting svgcheck
  Downloading https://files.pythonhosted.org/packages/c0/1c/8dd8afc962b69232899d38df39139e83527987bede90e2fc5ee4329c9d6c/svgcheck-0.6.0.tar.gz
Requirement already satisfied: lxml>=4.1.1 in /usr/local/lib/python2.7/site-packages (from svgcheck) (4.4.1)
Collecting requests>=2.5.0 (from svgcheck)
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 2.5MB/s 
Collecting six (from svgcheck)
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting rfctools_common>=0.6.0 (from svgcheck)
  Downloading https://files.pythonhosted.org/packages/68/1e/5f96c24714e2618634b118a83c4f67e7bdae7c1d91f5453d57ed9ae75bf7/rfctools_common-0.6.0.tar.gz (46kB)
     |████████████████████████████████| 51kB 10.2MB/s 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/51/y7h448qx69l3x8_g9glpk7sr0000gn/T/pip-install-g8DFMN/rfctools-common/setup.py", line 11, in <module>
        import six
    ImportError: No module named six
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/51/y7h448qx69l3x8_g9glpk7sr0000gn/T/pip-install-g8DFMN/rfctools-common/

**Comment by jimsch** [comment]
Please verify that "pip install six" fails on it's own.   What version of python are you using?

**Comment by jimsch** [comment]
I understand what is causing the problem, I am now trying to figure out why the code was written to do what it is doing.  Installing six in advance will deal with the problem.

**Comment by jimsch** [comment]
Fixed in build #106  - Version 6.0.1 has been dropped to PyPI so this should now work.

**Comment by fluffy** [comment]
That fix worked for me - thanks
